const data = {
    products: [
      {
        _id: '1',
        name: 'Core JAVA : Volume I',
        category: 'Programming',
        image: '/images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Oreilly',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Python for beginners',
        category: 'Programming',
        image: '/images/p2.png',
        price: 100,
        countInStock: 15,
        brand: 'Oreilly',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Learning SQL',
        category: 'Programming',
        image: '/images/p3.png',
        price: 220,
        countInStock: 0,
        brand: 'TataMcHill',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Modern C Language',
        category: 'Programming',
        image: '/images/p4.png',
        price: 78,
        countInStock: 8,
        brand: 'PH Publications',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Beautiful c++',
        category: 'Programming',
        image: '/images/p5.png',
        price: 65,
        countInStock: 20,
        brand: 'TataMcHill',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Programming PHP',
        category: 'Programming',
        image: '/images/p6.png',
        price: 139,
        countInStock: 12,
        brand: 'Khan publication',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;